language: julia
notifications:
  email: false
matrix:
  include:
    - os: linux
      julia: 0.7
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.0
      env: TESTCMD="xvfb-run julia"
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
script:
  - $TESTCMD --color=yes -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; Pkg.clone(pwd()); Pkg.build(\"Tachyons\"); Pkg.test(\"Tachyons\"; coverage=true)"
